#ifndef VK_DEVICE_EXT_FN
#define VK_DEVICE_EXT_FN(name)
#endif

#ifndef VK_INSTANCE_EXT_FN
#define VK_INSTANCE_EXT_FN(name)
#endif

#ifndef VK_INSTANCE_EXT
#define VK_INSTANCE_EXT(name)
#endif

#ifndef VK_DEVICE_EXT
#define VK_DEVICE_EXT(name)
#endif

VK_INSTANCE_EXT( VK_KHR_SURFACE_EXTENSION )
VK_INSTANCE_EXT( VK_KHR_XCB_SURFACE_EXTENSION )
VK_INSTANCE_EXT( VK_KHR_XLIB_SURFACE_EXTENSION )

VK_DEVICE_EXT( VK_KHR_SWAPCHAIN_EXTENSION )
VK_DEVICE_EXT( VK_KHR_MAINTENANCE1_EXTENSION )
VK_DEVICE_EXT( VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION )
VK_DEVICE_EXT( VK_KHR_EXTERNAL_SEMAPHORE_FD_EXTENSION )
VK_DEVICE_EXT( VK_KHR_EXTERNAL_MEMORY_EXTENSION )
VK_DEVICE_EXT( VK_KHR_EXTERNAL_SEMAPHORE_EXTENSION )
VK_DEVICE_EXT( VK_KHR_DEDICATED_ALLOCATION_EXTENSION )
VK_DEVICE_EXT( VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION )

VK_DEVICE_EXT_FN( GetMemoryFdKHR )
VK_DEVICE_EXT_FN( CreateXcbSurfaceKHR )
VK_DEVICE_EXT_FN( CreateSwapchainKHR )
VK_DEVICE_EXT_FN( DestroySwapchainKHR )
VK_DEVICE_EXT_FN( GetSwapchainImagesKHR )
VK_DEVICE_EXT_FN( AcquireNextImageKHR )
VK_DEVICE_EXT_FN( QueuePresentKHR )
VK_DEVICE_EXT_FN( GetPhysicalDeviceXcbPresentationSupportKHR )
VK_DEVICE_EXT_FN( GetImageMemoryRequirements2KHR )
VK_DEVICE_EXT_FN( GetBufferMemoryRequirements2KHR )

#undef VK_INSTANCE_EXT
#undef VK_INSTANCE_EXT_FN
#undef VK_DEVICE_EXT
#undef VK_DEVICE_EXT_FN
